name: parish_interest_survey_public

profile: parish_survey_portfolio

#seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

#seeds:
  # Builds seeds into '<your_schema_name>_raw'
  #parish_interest_survey_public:
  #  +schema: raw

models:
  parish_interest_survey_public:
    +static_analysis: strict
    # Materialize staging models as views, and marts as tables
    staging:
      +materialized: view
    marts:
      +materialized: table
